// Builds the Vibe A1 from the Vibe Robotics SDK's MuJoCo models
// (assets/robot/robots.json + parts.glb, generated by tools/build-robot.mjs).
//
// Hierarchy per MuJoCo body:  parent -> body(pos, quat) -> joint(rotation about axis) -> geoms + child bodies
// The robot sits under a root that converts MuJoCo Z-up (+Y = robot front) to
// three.js Y-up with the robot facing +Z.

import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';

export const SERVO_MESHES = new Set(['sts3215', 'sts3250']);
const SHELL_MESHES = /^(torso|head|back_cover)/;

// Friendly names for parts, keyed by CAD file-name prefix.
const PART_INFO = [
  ['torso', 'Torso shell', '3D-printed'],
  ['back_cover', 'Back cover', '3D-printed'],
  ['head', 'Head frame', '3D-printed'],
  ['leg_adapter', 'Leg adapter', '3D-printed'],
  ['leg_foundation', 'Leg foundation', '3D-printed'],
  ['shoulder', 'Shoulder bracket', '3D-printed'],
  ['tricep', 'Upper arm', '3D-printed'],
  ['bicep', 'Elbow bracket', '3D-printed'],
  ['wrist', 'Forearm', '3D-printed'],
  ['forearm', 'Forearm', '3D-printed'],
  ['paw', 'Gripper paw', '3D-printed'],
  ['thumb', 'Gripper thumb', '3D-printed'],
  ['hips', 'Hip bracket', '3D-printed'],
  ['thigh', 'Thigh', '3D-printed'],
  ['knee', 'Knee bracket', '3D-printed'],
  ['calf', 'Shin', '3D-printed'],
  ['ankle', 'Ankle bracket', '3D-printed'],
  ['foot', 'Foot', '3D-printed'],
  ['sts3215', 'STS3215 servo', '19.5 kg·cm @ 7.4 V'],
  ['sts3250', 'STS3250 servo', '50 kg·cm @ 12 V'],
  ['realsense_d435i', 'RealSense D435i', 'depth camera'],
  ['max4466', 'Microphone', 'MAX4466 board'],
];

export function partInfo(mesh) {
  const key = mesh.replace(/^(left|right)_/, '');
  for (const [prefix, name, note] of PART_INFO) if (key.startsWith(prefix)) return { name, note, file: mesh };
  return { name: mesh, note: '', file: mesh };
}

// Bus IDs from the Vibe A1 electronics guide (25-servo build).
export const SERVO_IDS = {
  right_shoulder_pitch: 1, right_shoulder_roll: 2, right_shoulder_yaw: 3, right_elbow_pitch: 4, right_wrist_yaw: 5, right_hand: 6,
  right_hip_pitch: 7, right_hip_roll: 8, right_hip_yaw: 9, right_knee: 10, right_ankle_pitch: 11, right_ankle_roll: 12,
  left_shoulder_pitch: 13, left_shoulder_roll: 14, left_shoulder_yaw: 15, left_elbow_pitch: 16, left_wrist_yaw: 17, left_hand: 18,
  left_hip_pitch: 19, left_hip_roll: 20, left_hip_yaw: 21, left_knee: 22, left_ankle_pitch: 23, left_ankle_roll: 24,
  head_yaw: 25,
};

/** "right_hip_pitch" -> "Hip pitch", "left_hand" -> "Gripper". */
export function jointLabel(name) {
  const s = name.replace(/^(left|right)_/, '').replace(/_/g, ' ').replace(/^hand$/, 'gripper');
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export async function loadRobotAssets(base = 'assets/robot/') {
  const loader = new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);
  const [gltf, trees] = await Promise.all([
    loader.loadAsync(base + 'parts.glb'),
    fetch(base + 'robots.json').then((r) => r.json()),
  ]);
  const parts = {};
  gltf.scene.traverse((o) => {
    // Keep each node's transform: KHR_mesh_quantization stores the de-quantization scale/offset there.
    if (o.isMesh) {
      o.geometry.computeBoundingBox();
      parts[o.name] = { geometry: o.geometry, position: o.position.clone(), quaternion: o.quaternion.clone(), scale: o.scale.clone() };
    }
  });
  return { parts, trees };
}

function materialFor(mesh, rgba, mats) {
  if (SERVO_MESHES.has(mesh)) return mats.servo;
  if (mesh === 'realsense_d435i') return mats.sensor;
  if (mesh.startsWith('max4466')) return mats.pcb;
  if (SHELL_MESHES.test(mesh)) return mats.shell;
  return rgba[0] < 0.9 ? mats.plasticGrey : mats.plastic;
}

const MJ_TO_THREE = new THREE.Quaternion()
  .setFromAxisAngle(new THREE.Vector3(0, 1, 0), Math.PI)
  .multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), -Math.PI / 2));

/**
 * A posable robot instance.
 *   root      Object3D in three.js space, feet on y = 0 at the zero pose
 *   model     MuJoCo-frame group (Z-up) under root; its position is the base (torso) origin
 *   joints    Map name -> { name, axis, range, group, body, angle, servo }
 *   bodies    [{ name, group, jointGroup, parent, data, meshes }]
 *   servos    [{ mesh, joint, id, center (local), body }]
 */
export class Robot {
  constructor(assets, variant, mats) {
    const tree = assets.trees[variant];
    this.variant = variant;
    this.mats = mats;
    this.actuators = tree.actuators;
    this.root = new THREE.Group();
    this.root.name = `vibe-${variant}`;
    this.model = new THREE.Group();
    this.model.quaternion.copy(MJ_TO_THREE);
    this.root.add(this.model);
    this.joints = new Map();
    this.bodies = [];
    this.meshes = [];

    tree.bodies.forEach((b, i) => {
      const body = new THREE.Group();
      body.name = b.name;
      body.position.fromArray(b.pos);
      body.quaternion.fromArray(b.quat);
      const jointGroup = new THREE.Group();
      jointGroup.name = b.joint ? b.joint.name : b.name + '_fixed';
      body.add(jointGroup);
      (b.parent >= 0 ? this.bodies[b.parent].jointGroup : this.model).add(body);
      const entry = { index: i, name: b.name, group: body, jointGroup, parent: b.parent, data: b, meshes: [], basePos: body.position.clone() };
      this.bodies.push(entry);
      if (b.joint) {
        this.joints.set(b.joint.name, {
          name: b.joint.name,
          axis: new THREE.Vector3().fromArray(b.joint.axis).normalize(),
          range: b.joint.range,
          group: jointGroup,
          body: entry,
          angle: 0,
          servo: null,
        });
      }
      for (const g of b.geoms) {
        const part = assets.parts[g.mesh];
        if (!part) continue;
        const holder = new THREE.Group();
        holder.position.fromArray(g.pos);
        holder.quaternion.fromArray(g.quat);
        const mesh = new THREE.Mesh(part.geometry, materialFor(g.mesh, g.rgba, mats));
        mesh.position.copy(part.position);
        mesh.quaternion.copy(part.quaternion);
        mesh.scale.copy(part.scale);
        mesh.castShadow = true;
        mesh.receiveShadow = true;
        mesh.name = g.mesh;
        mesh.userData = { kind: 'robot-part', mesh: g.mesh, info: partInfo(g.mesh), body: entry, holder, holderBase: holder.position.clone() };
        holder.add(mesh);
        jointGroup.add(holder);
        entry.meshes.push(mesh);
        this.meshes.push(mesh);
      }
    });

    this.root.updateMatrixWorld(true);
    const box = new THREE.Box3().setFromObject(this.model);
    this.model.position.y -= box.min.y;
    this.zeroBase = this.model.position.clone();
    this.root.updateMatrixWorld(true);
    this.height = box.max.y - box.min.y;
    this.assignServos();
  }

  /** Map each joint to the servo mesh whose centre lies closest to the joint axis. */
  assignServos() {
    const servos = this.meshes.filter((m) => SERVO_MESHES.has(m.userData.mesh));
    const centers = new Map(
      servos.map((m) => {
        const c = m.geometry.boundingBox.getCenter(new THREE.Vector3());
        return [m, c];
      }),
    );
    const world = (m) => centers.get(m).clone().applyMatrix4(m.matrixWorld);
    // score every (joint, nearby servo) pair, then assign the cheapest pairs first
    const pairs = [];
    const line = new THREE.Line3();
    const tmp = new THREE.Vector3();
    for (const j of this.joints.values()) {
      const origin = new THREE.Vector3().setFromMatrixPosition(j.group.matrixWorld);
      const dir = j.axis.clone().transformDirection(j.group.matrixWorld);
      line.set(origin.clone().addScaledVector(dir, -1), origin.clone().addScaledVector(dir, 1));
      const parentBody = this.bodies[j.body.parent];
      for (const m of servos) {
        if (m.userData.body !== parentBody && m.userData.body !== j.body) continue;
        const c = world(m);
        pairs.push({ j, m, cost: line.closestPointToPoint(c, false, tmp).distanceTo(c) + c.distanceTo(origin) * 0.15 });
      }
    }
    // most constrained joints first (e.g. the gripper has a single candidate), then cheapest pair
    const options = new Map();
    for (const p of pairs) options.set(p.j, (options.get(p.j) ?? 0) + 1);
    pairs.sort((a, b) => options.get(a.j) - options.get(b.j) || a.cost - b.cost);
    const takenJ = new Set();
    const takenM = new Set();
    this.servos = [];
    for (const { j, m } of pairs) {
      if (takenJ.has(j) || takenM.has(m)) continue;
      takenJ.add(j);
      takenM.add(m);
      const entry = { mesh: m, joint: j.name, id: SERVO_IDS[j.name] ?? null, center: centers.get(m) };
      m.userData.servo = entry;
      j.servo = entry;
      this.servos.push(entry);
    }
    this.servoCount = servos.length;
  }

  setJoint(name, angle) {
    const j = this.joints.get(name);
    if (!j) return;
    if (j.range) angle = THREE.MathUtils.clamp(angle, j.range[0], j.range[1]);
    j.angle = angle;
    j.group.quaternion.setFromAxisAngle(j.axis, angle);
  }

  setPose(pose) {
    for (const k in pose) this.setJoint(k, pose[k]);
  }

  /** Mass-weighted centre of mass in world space, from the CAD inertials. */
  centerOfMass(target = new THREE.Vector3()) {
    let m = 0;
    const p = new THREE.Vector3();
    target.set(0, 0, 0);
    for (const b of this.bodies) {
      const mass = b.data.inertial.mass;
      if (mass < 1e-6) continue;
      p.fromArray(b.data.inertial.pos).applyMatrix4(b.jointGroup.matrixWorld);
      target.addScaledVector(p, mass);
      m += mass;
    }
    return target.divideScalar(m);
  }

  get mass() {
    return this.bodies.reduce((s, b) => s + b.data.inertial.mass, 0);
  }

  body(name) {
    return this.bodies.find((b) => b.name === name);
  }
}
